const pptr=require('puppeteer'),assert=require('assert'),path=require('path'),fs=require('fs');
const url='file://'+path.resolve('2-HOST-ONLINE/index.html');
(async()=>{const b=await pptr.launch({headless:true});const errors=[];async function page(){const p=await b.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});return p}try{
const p=await page();await p.setViewport({width:1440,height:1000});await p.goto(url);await p.waitForSelector('#nav a');
// Priority: two different valid snapshots; IDB wins.
await p.evaluate(async()=>{const primary=blank(),secondary=blank();primary.profile.name='IndexedDB primary';secondary.profile.name='Local secondary';await idbSet(primary);lsSet(secondary);await load()});assert.equal(await p.evaluate(()=>S.profile.name),'IndexedDB primary');
assert.deepEqual(await p.evaluate(()=>[cents('0.29'),cents('12.01'),cents('100000.99'),cents('bad'),cents('2.001')]),[29,1201,10000099,null,null]);
const migration=await p.evaluate(()=>{const old=blank();old.version=3;delete old.cover;delete old.awards;old.applications=[{id:'old',company:'Test',role:'Role',salary:'$60,000.25'},{id:'notes',salary:'Negotiable 60–70k'}];const n=norm(migrate(old));return [n.version,n.applications[0].salaryCents,n.applications[1].salaryNote,n.awards.length,!!n.cover]});assert.deepEqual(migration,[5,6000025,'Negotiable 60–70k',0,true]);assert.equal(await p.evaluate(()=>migrate({version:4,applications:[{salary:'£45000'}]}).applications[0].currency),'GBP');
assert.equal(await p.evaluate(()=>{try{migrate({version:99});return false}catch(e){return true}}),true);
await p.evaluate(()=>{sampleMode=false;S=norm(migrate(sampleData()));S.profile.name='Alex Taylor';return save()});
for(const theme of ['light','dark']){await p.evaluate(t=>{S.settings.theme=t;render()},theme);for(const view of ['hub','bank','resume','cover','jobs','contacts','playbook','settings']){await p.evaluate(v=>{window.view=v;render()},view);await p.evaluate(()=>{document.querySelector('#toast').hidden=true;return document.fonts.ready});const missing=await p.$$eval('input:not([type=hidden]),select,textarea',els=>els.filter(e=>!e.labels?.length&&!e.getAttribute('aria-label')&&!e.getAttribute('aria-labelledby')).map(e=>e.outerHTML));assert.deepEqual(missing,[],`${theme}/${view} field labels`);const empty=await p.$$eval('button',els=>els.filter(e=>!e.textContent.trim()&&!e.getAttribute('aria-label')&&!e.getAttribute('aria-labelledby')).map(e=>e.outerHTML));assert.deepEqual(empty,[]);await p.screenshot({path:`output/audit/${theme}-${view}.png`});}
await p.evaluate(()=>{view='resume';S.resume.template='sidebar';render()});await p.screenshot({path:`output/audit/${theme}-sidebar.png`});
await p.setViewport({width:390,height:844});for(const view of ['hub','bank','resume','cover','jobs','contacts','playbook','settings']){await p.evaluate(v=>{window.view=v;render()},view);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`page overflow ${theme}/${view}`);await p.screenshot({path:`output/audit/${theme}-mobile-${view}.png`});}await p.setViewport({width:1440,height:1000});}
await p.evaluate(()=>{view='resume';render()});await p.click('[data-act=edit-profile]');await p.waitForSelector('#dlg[open]');assert.equal(await p.$eval('#dlg input',e=>e===document.activeElement),true);await p.keyboard.press('Escape');assert.equal(await p.$eval('#dlg',e=>e.open),false);
await p.evaluate(()=>{view='bank';bankTab='profile';S.profile.name='<img src=x onerror=alert(1)>';render()});assert.equal(await p.$$eval('#view img',e=>e.length),0);assert.equal(await p.$eval('#profile input[name=name]',e=>e.value),'<img src=x onerror=alert(1)>');
await p.evaluate(()=>{S.applications=[];view='jobs';render();edit('applications')});await p.type('#dlg [name=company]','Test employer');await p.type('#dlg [name=role]','Coordinator');await p.type('#dlg [name=salaryCents]','75000.29');await p.click('#dlg button[type=submit]');assert.equal(await p.evaluate(()=>S.applications[0].salaryCents),7500029);await p.evaluate(()=>saveQueue);await p.reload();await p.waitForSelector('#nav a');assert.equal(await p.evaluate(()=>S.applications[0].salaryCents),7500029);
// Simulate denied storage: test local fallback, then memory only.
for(const localAllowed of [true,false]){const q=await page();await q.evaluateOnNewDocument(allow=>{Object.defineProperty(window,'indexedDB',{get(){throw new DOMException('Denied','SecurityError')}});if(!allow)Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Denied','SecurityError')}})},localAllowed);await q.goto(url);await q.waitForSelector('#nav a');await q.evaluate(async()=>{S.profile.name='Fallback saved';await save();await load()});assert.equal(await q.evaluate(()=>S.profile.name),'Fallback saved');await q.close()}
const ratios=await p.evaluate(()=>{function lum(c){return c.match(/\d+(?:\.\d+)?/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0)}function ratio(a,b){let x=lum(a),y=lum(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)}const rows=[];for(const theme of ['light','dark'])for(const accent of Object.keys(ACCENTS)){S.settings.theme=theme;S.settings.accent=accent;view='resume';render();const el=document.querySelector('.primary'),cs=getComputedStyle(el);rows.push([theme,accent,ratio(cs.color,cs.backgroundColor)]);const hint=document.querySelector('.tpl-btn[aria-pressed=true] small'),hc=getComputedStyle(hint),bc=getComputedStyle(hint.closest('button'));rows.push([theme,accent+' selected hint',ratio(hc.color,bc.backgroundColor)])}for(const accent of Object.keys(RESUME_ACCENTS)){S.resume.template='sidebar';S.resume.accent=accent;render();const el=document.querySelector('.resume-side p'),n=document.createElement('span');n.style.color=RESUME_ACCENTS[accent];document.body.append(n);rows.push(['resume',accent,ratio(getComputedStyle(el).color,getComputedStyle(n).color)]);n.remove()}return rows});assert(ratios.every(x=>x[2]>=4.5),JSON.stringify(ratios.filter(x=>x[2]<4.5)));fs.writeFileSync('output/audit/contrast-results.json',JSON.stringify(ratios,null,2));
const stuck=await page();await stuck.evaluateOnNewDocument(()=>{Object.defineProperty(window,'indexedDB',{value:{open(){return {}}}})});await stuck.goto(url);await stuck.waitForSelector('#nav a',{timeout:7000});assert(await stuck.evaluate(()=>!!S.profile));await stuck.close();
const newer=await page();await newer.goto(url);await newer.waitForSelector('#nav a');assert(await newer.evaluate(async()=>{await idbSet({version:99,profile:{name:'Keep newer data'}});await load();await save();return storageReadOnly&&(await idbGet()).profile.name==='Keep newer data'}));await newer.close();
assert.deepEqual(errors,[]);fs.writeFileSync('output/audit/test-results.json',JSON.stringify({status:'PASS',consoleErrors:errors,migrations:'v3 to v5',storage:['IndexedDB priority','localStorage fallback','memory fallback'],screenshots:34},null,2));console.log('PASS: storage priority/fallbacks, migrations, integer cents, CRUD/reload, escaping, modal keyboard, labelled controls, all views light/dark desktop/mobile; zero console errors.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
